language: go
go:
  - 1.15.6

sudo: required

os:
  - linux
  - osx

script:
  - echo "test"
  - make test
  - go test -race -coverprofile=coverage.txt -covermode=atomic

before_install:
  - go get -t -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)