language: go
go:
  - 1.15.6

sudo: required

os:
  - linux
  - osx

notifications:  # 邮箱通知
  email: freeit@126.com

go_import_path:
  - github.com/gin-gonic/gin
  - github.com/pkg/errors
  - github.com/smartystreets/goconvey

before_install: # 主要安装一些系统依赖, true跳过
  - go mod tidy

install: true # 安装

script:
  - echo "run"
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go test -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)