language: go
go:
  - 1.15.6

sudo: required

os:
  - linux
  - osx

notifications:  # 邮箱通知
  email: freeit@126.com

before_install: # 主要安装一些系统依赖

install: # 安装
  - go mod tidy

script:
  - echo "run"
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)